### ISSUE TITLE
Not working for me the session remains .starting

### ISSUE THREAD

**Issue by arpitjain03** [hansemannn/facebook-live-ios#11]
I have tried everything possible, but unable to find out why session keeps .starting only and never reaches .started.

**Comment by iStefo** [comment]
Can't confirm, I successfully tried out streaming today and it worked basically as described in the readme.

**Comment by hansemannn** [comment]
Thanks for the confirmation! Probably missing privacy-keys or invalid configuration in the Facebook dev-console. Closing for now.
