### ISSUE TITLE
Is there anyway to solve this issue in your project?

### ISSUE THREAD

**Issue by MS0401** [hansemannn/facebook-live-ios#17]
Hi,

I have checked your project carefully again.
Then I realized your purpose.

So I have reinstall cocoapods correctly within your pods file.

then I have got this error.
![screenshot_6](https://user-images.githubusercontent.com/39023036/43911098-63457d5a-9bb3-11e8-9161-0bce2aac96ae.png)

I think you can fix this error in a short time.

Looking forward for your response.

Best regards.
Gojko Maric

**Comment by hansemannn** [comment]
Dupe of #13
