### ISSUE TITLE
How to stream page and group, event live video using your project?

### ISSUE THREAD

**Issue by MS0401** [hansemannn/facebook-live-ios#19]
Hello, Hans!

Thanks!

I am a man that love your code style.
Your project is great one.
I didn't still discovered FB streaming ios app such as your project.

Your project is working well.

I appreciate your project and professional skills.
I have many learned from you how to stream live video in facebook.

Very nice project!!!

And now, I have one question.

I have already implemented only user's timeline live video streaming.
now, I have to implement pages and group, event live video streaming function also.

In your project, you wrote that have to replace page id or group id, event id in "audience" parameter of FBLiveVideo class.

So, my problem is how to get page id and group id and event id.

I have googled many times to find any solution(honestly full two days).
But, I have not still found any solution about my problem.
![screenshot_5](https://user-images.githubusercontent.com/39023036/46247240-3463ef80-c3bd-11e8-9a73-daf51fc0dd2c.png)

Would you please help me more?

Thanks for your code and professional skills.
Best regards!
From Gojko Maric

**Comment by hansemannn** [comment]
User-ID: https://findmyfbid.com/
Group-ID: http://lookup-id.com/
