### ISSUE TITLE
Can not sharing video to public 

### ISSUE THREAD

**Issue by jack3010** [hansemannn/facebook-live-ios#2]
Hi there. 
I really really interesting with the project. I also saw the code but it only accepted sharing a video for "Only me" mode.
`self.liveVideo.privacy = .me`
`self.liveVideo.audience = "me" // or your user-id, page-id, event-id, group-id, ...`
Now I also changed code like 
`self.liveVideo.privacy = .friends`
`self.liveVideo.audience = "FRIEND" // or your user-id, page-id, event-id, group-id, ...`
But it can not record video,then. 
Could you suggest me another way to record and public video with "Public" or "Friends" mode?
Thanks.

**Comment by hansemannn** [comment]
Hey @jack3010, thanks for reaching out! Basically, the `privacy` flag looks correct, but the `audience` one needs the user-id, username, page-id as described in the comment. You can think of it like the base-path of a graph-request `GET me/friends`, `GET me/livevideo`. So your correct usage would be:
```swift
self.liveVideo.privacy = .friends
self.liveVideo.audience = "me"
```
This means that your video can be seen by your friends as well and is started from yourselfs page (I made it generic so you can also start live-videos from Facebook pages you host. Maybe I should rename `audience` to something less confusing? Any suggestions? Hope it works now, thx!

**Comment by hansemannn** [comment]
Closing for now, let me now if you have an improvement for the property naming!
