### ISSUE TITLE
Text/Image Captions in Live Stream

### ISSUE THREAD

**Issue by keenyosh** [hansemannn/facebook-live-ios#3]
Great starter app for live streaming, thank you!
I'd like to request a feature that will display text and images in a live stream for captioning.  Or an idea of how to implement this.  I've done this for simple video recordings, but have no clue how to achieve this in a live stream.  I'm thinking it should be similar right?

**Comment by hansemannn** [comment]
Great idea! Maybe rather an overlay view that can be passed to keep it dynamic. What do you think?

**Comment by keenyosh** [comment]
Yes, that would be pretty awesome!

**Comment by hansemannn** [comment]
Overlays are now supported since https://github.com/hansemannn/facebook-live-ios/commit/9a1b0dc970062fd2180d19d1e577941de2f3fa50, use with the `overlay` property!
