### ISSUE TITLE
Content Tags

### ISSUE THREAD

**Issue by tommy-b-10** [hansemannn/facebook-live-ios#6]
Hi, I have tried using an array of strings as the content type eg: ["cats","boats"] however it is giving an error when doing the POST request. What is the correct format for using the content_tags option?

**Comment by hansemannn** [comment]
Hey there! See the [Facebook docs](https://developers.facebook.com/docs/graph-api/reference/live-video/) for more infos. Basically, you need to specify ID's here, not just words. There are content tags that can be resolved by calling to `/search?type=adinterest&q=couscous` and then use the resulting ID's.  Quote:
> Tags that describe the contents of the video. Use search endpoint with type=adinterest to get possible IDs.
