### ISSUE TITLE
Can i avoid creating app on developers.facebook.com and stream directly on the page?

### ISSUE THREAD

**Issue by st4ycool** [hansemannn/facebook-live-ios#9]
Sorry for lack of details in my previous issue.
I meant is there a way to stream on facebook bypassing creating app on facebook.developers.com: http://i.imgur.com/p1TPWRE.jpg . I have some issues with this, and just tryna find a way to solve it.
P.S. question is not only about hansemannn/facebook-live-ios, but generally about fb streams.
Thank you

**Comment by keenyosh** [comment]
You can bypass creating a Facebook app if you take out the login functionality in facebook-live-ios and use it only as a video coder.

You would have to create a stream key from Facebook and implement a way to retrieve the key within the ios app and set the appropriate properties.

**Comment by st4ycool** [comment]
Is it legal? ) I read fb docs and they are clear about mobile streaming apps - they are forbidden.
Thanks anyway!

**Comment by keenyosh** [comment]
Forbidden only if it uses a mobile device camera.  External cameras are okay.

**Comment by hansemannn** [comment]
Closing as answered, thanks!
